apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp
  namespace: wfdemo
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - image: luisredda/harness-java-demo-k8s:latest-wf
        imagePullPolicy: IfNotPresent
        name: harness-java-demo-k8s
      restartPolicy: Always
      terminationGracePeriodSeconds: 30